/* A packrat parser generated by PackCC 1.5.0 */

#ifndef PCC_INCLUDED_GML_H
#define PCC_INCLUDED_GML_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct gml_context_tag gml_context_t;

gml_context_t *gml_create(void *auxil);
int gml_parse(gml_context_t *ctx, int *ret);
void gml_destroy(gml_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_GML_H */
