
/*
 *  Copyright 2021
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  These are the four essential freedoms with GNU GPL software:
 *  1: freedom to run the program, for any purpose
 *  2: freedom to study how the program works, and change it to make it do what you wish
 *  3: freedom to redistribute copies to help your Free Software friends
 *  4: freedom to distribute copies of your modified versions to your Free Software friends
 *   ,           ,
 *  /             \
 * ((__-^^-,-^^-__))
 * `-_---'  `---_-'
 *  `--|o`   'o|--'
 *      \  `  /
 *       ): :(
 *       :o_o:
 *        "-"
 *
 * SPDX-License-Identifier: GPL-3.0+
 * License-Filename: LICENSE
 */

/* parse bgv graph data generated by graalvm and other software from oracle */

#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zlib.h>

#include "splay-tree.h"
#include "main.h"
#include "bgv.h"
#include "bgvparser.h"
#include "dpmem.h"
#include "dot.tab.h"

static char *curfname = NULL;

static int bgverror = 0;

static int bgvdebug = 0;

/* */
int bgvparse(struct gml_graph *g, gzFile f, char *fname, char *argv0)
{
	int status = 0;

	if (g == NULL || 1 /* test only */ ) {
		return (0);
	}

	curfname = fname;

	/* no errors */
	bgverror = 0;

	bgvdebug = yydebug;

	status = runbgvparse(f, bgvdebug);

	if (bgvdebug) {
		printf("%s(): status=%d\n", __func__, status);
	}

	return (0);
}

/* end */
