
/*
 *  Copyright 2021
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  These are the four essential freedoms with GNU GPL software:
 *  1: freedom to run the program, for any purpose
 *  2: freedom to study how the program works, and change it to make it do what you wish
 *  3: freedom to redistribute copies to help your Free Software friends
 *  4: freedom to distribute copies of your modified versions to your Free Software friends
 *   ,           ,
 *  /             \
 * ((__-^^-,-^^-__))
 * `-_---'  `---_-'
 *  `--|o`   'o|--'
 *      \  `  /
 *       ): :(
 *       :o_o:
 *        "-"
 *
 * SPDX-License-Identifier: GPL-3.0+
 * License-Filename: LICENSE
 */

/* parse bgv graph data generated by graalvm and other software from oracle */

#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zlib.h>

#include "splay-tree.h"
#include "main.h"
#include "bgv.h"
#include "bgvparser.h"
#include "dpmem.h"

static gzFile cf = (gzFile) 0;
static int db = 0;

static int magic(void);

/* parse bgv file return 0 if oke */
int runbgvparse(gzFile f, int debug)
{
	int status = 0;
	db = debug;
	cf = f;
	status = magic();
	if (status) {
		return (1);
	}
	db = 0;
	cf = (gzFile) 0;
	return (0);
}

/* the magic is BIGV */
static int magic(void)
{
	int ch = 0;
	ch = gzgetc(cf);
	if (ch != 'B') {
		return (1);
	}
	ch = gzgetc(cf);
	if (ch != 'I') {
		return (1);
	}
	ch = gzgetc(cf);
	if (ch != 'G') {
		return (1);
	}
	ch = gzgetc(cf);
	if (ch != 'V') {
		return (1);
	}
	if (db) {
		printf("%s(): magic BIGV found\n", __func__);
	}
	return (0);
}

/* end. */
