
#line 3 "lex.hl.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
#define yy_create_buffer hl_create_buffer
#define yy_delete_buffer hl_delete_buffer
#define yy_scan_buffer hl_scan_buffer
#define yy_scan_string hl_scan_string
#define yy_scan_bytes hl_scan_bytes
#define yy_init_buffer hl_init_buffer
#define yy_flush_buffer hl_flush_buffer
#define yy_load_buffer_state hl_load_buffer_state
#define yy_switch_to_buffer hl_switch_to_buffer
#define yypush_buffer_state hlpush_buffer_state
#define yypop_buffer_state hlpop_buffer_state
#define yyensure_buffer_stack hlensure_buffer_stack
#define yy_flex_debug hl_flex_debug
#define yyin hlin
#define yyleng hlleng
#define yylex hllex
#define yylineno hllineno
#define yyout hlout
#define yyrestart hlrestart
#define yytext hltext
#define yywrap hlwrap
#define yyalloc hlalloc
#define yyrealloc hlrealloc
#define yyfree hlfree

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
#ifdef yy_create_buffer
#define hl_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer hl_create_buffer
#endif

#ifdef yy_delete_buffer
#define hl_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer hl_delete_buffer
#endif

#ifdef yy_scan_buffer
#define hl_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer hl_scan_buffer
#endif

#ifdef yy_scan_string
#define hl_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string hl_scan_string
#endif

#ifdef yy_scan_bytes
#define hl_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes hl_scan_bytes
#endif

#ifdef yy_init_buffer
#define hl_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer hl_init_buffer
#endif

#ifdef yy_flush_buffer
#define hl_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer hl_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define hl_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state hl_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define hl_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer hl_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define hlpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state hlpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define hlpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state hlpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define hlensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack hlensure_buffer_stack
#endif

#ifdef yylex
#define hllex_ALREADY_DEFINED
#else
#define yylex hllex
#endif

#ifdef yyrestart
#define hlrestart_ALREADY_DEFINED
#else
#define yyrestart hlrestart
#endif

#ifdef yylex_init
#define hllex_init_ALREADY_DEFINED
#else
#define yylex_init hllex_init
#endif

#ifdef yylex_init_extra
#define hllex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra hllex_init_extra
#endif

#ifdef yylex_destroy
#define hllex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy hllex_destroy
#endif

#ifdef yyget_debug
#define hlget_debug_ALREADY_DEFINED
#else
#define yyget_debug hlget_debug
#endif

#ifdef yyset_debug
#define hlset_debug_ALREADY_DEFINED
#else
#define yyset_debug hlset_debug
#endif

#ifdef yyget_extra
#define hlget_extra_ALREADY_DEFINED
#else
#define yyget_extra hlget_extra
#endif

#ifdef yyset_extra
#define hlset_extra_ALREADY_DEFINED
#else
#define yyset_extra hlset_extra
#endif

#ifdef yyget_in
#define hlget_in_ALREADY_DEFINED
#else
#define yyget_in hlget_in
#endif

#ifdef yyset_in
#define hlset_in_ALREADY_DEFINED
#else
#define yyset_in hlset_in
#endif

#ifdef yyget_out
#define hlget_out_ALREADY_DEFINED
#else
#define yyget_out hlget_out
#endif

#ifdef yyset_out
#define hlset_out_ALREADY_DEFINED
#else
#define yyset_out hlset_out
#endif

#ifdef yyget_leng
#define hlget_leng_ALREADY_DEFINED
#else
#define yyget_leng hlget_leng
#endif

#ifdef yyget_text
#define hlget_text_ALREADY_DEFINED
#else
#define yyget_text hlget_text
#endif

#ifdef yyget_lineno
#define hlget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno hlget_lineno
#endif

#ifdef yyset_lineno
#define hlset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno hlset_lineno
#endif

#ifdef yywrap
#define hlwrap_ALREADY_DEFINED
#else
#define yywrap hlwrap
#endif

/* %endif */

#ifdef yyalloc
#define hlalloc_ALREADY_DEFINED
#else
#define yyalloc hlalloc
#endif

#ifdef yyrealloc
#define hlrealloc_ALREADY_DEFINED
#else
#define yyrealloc hlrealloc
#endif

#ifdef yyfree
#define hlfree_ALREADY_DEFINED
#else
#define yyfree hlfree
#endif

/* %if-c-only */

#ifdef yytext
#define hltext_ALREADY_DEFINED
#else
#define yytext hltext
#endif

#ifdef yyleng
#define hlleng_ALREADY_DEFINED
#else
#define yyleng hlleng
#endif

#ifdef yyin
#define hlin_ALREADY_DEFINED
#else
#define yyin hlin
#endif

#ifdef yyout
#define hlout_ALREADY_DEFINED
#else
#define yyout hlout
#endif

#ifdef yy_flex_debug
#define hl_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug hl_flex_debug
#endif

#ifdef yylineno
#define hllineno_ALREADY_DEFINED
#else
#define yylineno hllineno
#endif

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef YYFLEX_INTTYPES_DEFINED
#define YYFLEX_INTTYPES_DEFINED

/* Prefer C99 integer types if available. */
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
/* Include <inttypes.h> and not <stdint.h> because Solaris 2.6 has the former
 * and not the latter.
 */
#include <inttypes.h>
#define YYFLEX_USE_STDINT
#else
#if defined(_MSC_VER) && _MSC_VER >= 1600
/* Visual C++ 2010 does not define __STDC_VERSION__ and has <stdint.h> but not
 * <inttypes.h>.
 */
#include <stdint.h>
#define YYFLEX_USE_STDINT
#endif
#endif
#ifdef YYFLEX_USE_STDINT
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef unsigned char flex_uint8_t;
typedef short int flex_int16_t;
typedef unsigned short int flex_uint16_t;
#ifdef __STDC__
typedef signed char flex_int8_t;
/* ISO C only requires at least 16 bits for int. */
#include <limits.h>
#if UINT_MAX >= 4294967295
#define YYFLEX_INT32_DEFINED
typedef int flex_int32_t;
typedef unsigned int flex_uint32_t;
#endif
#else
typedef char flex_int8_t;
#endif
#ifndef YYFLEX_INT32_DEFINED
typedef long int flex_int32_t;
typedef unsigned long int flex_uint32_t;
#endif
#endif
#endif /* YYFLEX_INTTYPES_DEFINED */

/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
#define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
#define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state {
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;	/* input buffer */
	char *yy_buf_pos;	/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	int yy_bs_lineno;
		      /**< The line count. */
	int yy_bs_column;
		      /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE *yy_buffer_stack = NULL;	 /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */
/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart(FILE * input_file);
void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer);
YY_BUFFER_STATE yy_create_buffer(FILE * file, int size);
void yy_delete_buffer(YY_BUFFER_STATE b);
void yy_flush_buffer(YY_BUFFER_STATE b);
void yypush_buffer_state(YY_BUFFER_STATE new_buffer);
void yypop_buffer_state(void);

static void yyensure_buffer_stack(void);
static void yy_load_buffer_state(void);
static void yy_init_buffer(YY_BUFFER_STATE b, FILE * file);
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer(char *base, yy_size_t size);
YY_BUFFER_STATE yy_scan_string(const char *yy_str);
YY_BUFFER_STATE yy_scan_bytes(const char *bytes, int len);

/* %endif */

void *yyalloc(yy_size_t);
void *yyrealloc(void *, yy_size_t);
void yyfree(void *);

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define hlwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state(void);
static yy_state_type yy_try_NUL_trans(yy_state_type current_state);
static int yy_get_next_buffer(void);
static void yynoreturn yy_fatal_error(const char *msg);

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 15
#define YY_END_OF_BUFFER 16
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info {
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
};
static const flex_int16_t yy_accept[40] = { 0,
	13, 13, 16, 14, 3, 4, 2, 5, 14, 14,
	13, 14, 6, 10, 9, 0, 2, 0, 0, 11,
	0, 0, 12, 0, 13, 8, 0, 7, 6, 0,
	7, 0, 0, 0, 0, 1, 1, 1, 0
};

static const YY_CHAR yy_ec[256] = { 0,
	1, 1, 1, 1, 1, 1, 1, 1, 2, 3,
	1, 4, 5, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 4, 6, 7, 1, 1, 1, 1, 8, 1,
	1, 1, 1, 1, 9, 1, 10, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 11,
	12, 13, 1, 1, 14, 14, 14, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
	1, 15, 1, 1, 1, 1, 14, 14, 14, 14,

	14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
	14, 14, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1
};

static const YY_CHAR yy_meta[16] = { 0,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1
};

static const flex_int16_t yy_base[43] = { 0,
	0, 0, 54, 55, 55, 42, 48, 13, 10, 11,
	9, 38, 21, 55, 55, 44, 45, 37, 13, 55,
	0, 14, 55, 0, 23, 55, 38, 32, 31, 35,
	29, 33, 32, 31, 26, 31, 55, 35, 55, 32,
	29, 20
};

static const flex_int16_t yy_def[43] = { 0,
	39, 1, 39, 39, 39, 39, 39, 39, 40, 41,
	39, 39, 39, 39, 39, 39, 39, 39, 40, 39,
	40, 41, 39, 41, 39, 39, 39, 39, 39, 39,
	39, 42, 42, 42, 39, 39, 39, 39, 0, 39,
	39, 39
};

static const flex_int16_t yy_nxt[71] = { 0,
	4, 5, 6, 7, 8, 4, 9, 10, 11, 12,
	13, 14, 15, 11, 4, 18, 20, 25, 23, 20,
	33, 23, 25, 16, 21, 24, 27, 21, 24, 22,
	28, 25, 19, 37, 29, 38, 25, 37, 36, 35,
	34, 34, 31, 32, 29, 31, 30, 16, 17, 27,
	26, 17, 16, 39, 3, 39, 39, 39, 39, 39,
	39, 39, 39, 39, 39, 39, 39, 39, 39, 39
};

static const flex_int16_t yy_chk[71] = { 0,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 8, 9, 11, 10, 19,
	42, 22, 11, 8, 9, 10, 13, 19, 22, 41,
	13, 25, 40, 36, 13, 36, 25, 38, 35, 34,
	33, 32, 31, 30, 29, 28, 27, 18, 17, 16,
	12, 7, 6, 3, 39, 39, 39, 39, 39, 39,
	39, 39, 39, 39, 39, 39, 39, 39, 39, 39
};

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[16] = { 0,
	1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
};

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[15] = { 0,
	125, 127, 128, 129, 130, 132, 190, 240, 246, 252,
	258, 314, 370, 516
};

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "dphl.l"
/*
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0+
 * License-Filename: LICENSE
 */
/* dphl.* is about Dot Parsing Html Labels */
/*
 * <br    /> is oke but < br/> not or <br/ > is not oke
 * <br/> is lexed as token "<br" and token "/>"
 */
/* gcc-11 analyzer has several problems with the flex-2.4.6 generated lexers, even with own customized skeleton */
#line 30 "dphl.l"

#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <strings.h>

#include "splay-tree.h"
#include "lex.yy.h"
#include "dot.tab.h"
#include "dp.h"
#include "dpus.h"
#include "dphlparser.h"
#include "dphl.h"
#include "dpmem.h"

/* use GNU GCC compiler builtin strlen */
#undef YY_NEED_STRLEN

/* temp buffer */
static char *tmp = NULL;
static char *pt = NULL;
static char *q = NULL;

/* ws */
static int skipws = 1;

/* own yyalloc
 * void *yyalloc (size_t n) { return(calloc(1,n)); }
 * void yyfree (void *ptr) { if(ptr) { free (ptr); } return; }
 * void *yyrealloc (void *ptr, size_t n) { return (realloc (ptr,n)); }
 */

#line 875 "lex.hl.c"
#line 66 "dphl.l"
	/* use own yyalloc
	 * %option noyyalloc
	 * %option noyyfree
	 * %option noyyrealloc
	 */
	/* no yywrap() at end-of-file */
	/* do not push back chars in stream function() */
	/* no input() function */
#define YY_NO_INPUT 1
	/* input does not come from a tty. */
	/* no yywrap() at end of file */
	/* 8-bits scanner */
	/* use nameprefix for routines */
	/* add debug output */
	/* use clib to read data */
	/* line no */
	/* "string" as in var="value" */
	/* 'string' as in var='value' */
	/* chars in a <var> */
	/* chars in a tag with a '-' for point-size */
#line 897 "lex.hl.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals(void);

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy(void);

int yyget_debug(void);

void yyset_debug(int debug_flag);

YY_EXTRA_TYPE yyget_extra(void);

void yyset_extra(YY_EXTRA_TYPE user_defined);

FILE *yyget_in(void);

void yyset_in(FILE * _in_str);

FILE *yyget_out(void);

void yyset_out(FILE * _out_str);

int yyget_leng(void);

char *yyget_text(void);

int yyget_lineno(void);

void yyset_lineno(int _line_number);

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap(void);
#else
extern int yywrap(void);
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT

#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy(char *, const char *, int);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(const char *);
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput(void);
#else
static int input(void);
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex(void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL {
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;

	if (!(yy_init)) {
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if (!(yy_start))
			(yy_start) = 1;	/* first start state */

		if (!yyin)
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if (!yyout)
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if (!YY_CURRENT_BUFFER) {
			yyensure_buffer_stack();
			YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE);
		}

		yy_load_buffer_state();
	}

	{
/* %% [7.0] user's declarations go here */
#line 123 "dphl.l"

#line 1178 "lex.hl.c"

		while ( /*CONSTCOND*/ 1) {	/* loops until end-of-file is reached */
			/* %% [8.0] yymore()-related code goes here */
			yy_cp = (yy_c_buf_p);

			/* Support of yytext. */
			*yy_cp = (yy_hold_char);

			/* yy_bp points to the position in yy_ch_buf of the start of
			 * the current run.
			 */
			yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
			yy_current_state = (yy_start);
yy_match:
			do {
				YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
				if (yy_accept[yy_current_state]) {
					(yy_last_accepting_state) = yy_current_state;
					(yy_last_accepting_cpos) = yy_cp;
				}
				while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
					yy_current_state = (int)yy_def[yy_current_state];
					if (yy_current_state >= 40)
						yy_c = yy_meta[yy_c];
				}
				yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
				++yy_cp;
			}
			while (yy_current_state != 39);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
			yy_act = yy_accept[yy_current_state];

			YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

			if (yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act]) {
				int yyl;
				for (yyl = 0; yyl < yyleng; ++yyl)
					if (yytext[yyl] == '\n')
						yylineno++;
				;
			}

do_action:			/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
			if (yy_flex_debug) {
				if (yy_act == 0)
					fprintf(stderr, "--scanner backing up\n");
				else if (yy_act < 15)
					fprintf(stderr, "--accepting rule at line %ld (\"%s\")\n",
						(long)yy_rule_linenum[yy_act], yytext);
				else if (yy_act == 15)
					fprintf(stderr, "--accepting default rule (\"%s\")\n", yytext);
				else if (yy_act == 16)
					fprintf(stderr, "--(end of buffer or a NUL)\n");
				else
					fprintf(stderr, "--EOF (start condition %d)\n", YY_START);
			}

			switch (yy_act) {	/* beginning of action switch */
/* %% [13.0] actions go here */
			case 0:	/* must back up */
				/* undo the effects of YY_DO_BEFORE_ACTION */
				*yy_cp = (yy_hold_char);
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;

			case 1:
/* rule 1 can match eol */
				YY_RULE_SETUP
#line 125 "dphl.l"
				{	/* skip comment and it does not allow <> chars in it or nested comments */
				}
				YY_BREAK case 2:YY_RULE_SETUP
#line 127 "dphl.l"
				{	/* skip form feed chars and spaces */
				} YY_BREAK case 3:YY_RULE_SETUP
#line 128 "dphl.l"
				{	/* skip tabs */
				} YY_BREAK case 4:
/* rule 4 can match eol */
				 YY_RULE_SETUP
#line 129 "dphl.l"
				{	/* skip new line *//* lexer does update yylineno */
				} YY_BREAK case 5:YY_RULE_SETUP
#line 130 "dphl.l"
				{	/* skip carriage return */
				} YY_BREAK case 6:YY_RULE_SETUP
#line 132 "dphl.l"
				{
					hlylval.string = dp_uniqstr(yytext);
					/* start of tag */
					if (strcasecmp(yytext, "<b") == 0) {
						skipws = 0;
						return (HL_B);
					} else if (strcasecmp(yytext, "<br") == 0) {
						skipws = 0;
						dphl_rbr();
						return (HL_BR);
					} else if (strcasecmp(yytext, "<font") == 0) {
						skipws = 0;
						return (HL_FONT);
					} else if (strcasecmp(yytext, "<hr") == 0) {
						dphl_rhr();
						return (HL_HR);
					} else if (strcasecmp(yytext, "<html") == 0) {
						return (HL_HTML);
					} else if (strcasecmp(yytext, "<i") == 0) {
						skipws = 0;
						return (HL_I);
					} else if (strcasecmp(yytext, "<img") == 0) {
						return (HL_IMG);
					} else if (strcasecmp(yytext, "<o") == 0) {
						skipws = 0;
						return (HL_O);
					} else if (strcasecmp(yytext, "<s") == 0) {
						skipws = 0;
						return (HL_S);
					} else if (strcasecmp(yytext, "<sub") == 0) {
						skipws = 0;
						return (HL_SUB);
					} else if (strcasecmp(yytext, "<sup") == 0) {
						skipws = 0;
						return (HL_SUP);
					} else if (strcasecmp(yytext, "<table") == 0) {
						return (HL_TABLE);
					} else if (strcasecmp(yytext, "<th") == 0) {
						/* undocumented that "th" is same as "td" */
						return (HL_TD);
					} else if (strcasecmp(yytext, "<td") == 0) {
						return (HL_TD);
					} else if (strcasecmp(yytext, "<tr") == 0) {
						return (HL_TR);
					} else if (strcasecmp(yytext, "<u") == 0) {
						skipws = 0;
						return (HL_U);
					} else if (strcasecmp(yytext, "<vr") == 0) {
						dphl_rvr();
						return (HL_VR);
					} else {
						/* this is a unknown tag at start */
						memset(dp_errmsg, 0, 256);
						snprintf(dp_errmsg, (256 - 1),
							 "%s(): unknown start tag `%s' in html string at line %d\n", __func__,
							 yytext, hllineno);
						return (EOF);
					}
				}
				YY_BREAK case 7:YY_RULE_SETUP
#line 190 "dphl.l"
				{
					hlylval.string = dp_uniqstr(yytext);
					/* end tag */
					if (strcasecmp(yytext, "</b") == 0) {
						return (HL_C_B);
					} else if (strcasecmp(yytext, "</br") == 0) {
						/* undocumented that <br></br> is same as <br/> */
						return (HL_C_BR);
					} else if (strcasecmp(yytext, "</font") == 0) {
						return (HL_C_FONT);
					} else if (strcasecmp(yytext, "</html") == 0) {
						return (HL_C_HTML);
					} else if (strcasecmp(yytext, "</hr") == 0) {
						/* it seems <hr></hr> could be same as <hr/> */
						return (HL_C_HR);
					} else if (strcasecmp(yytext, "</i") == 0) {
						return (HL_C_I);
					} else if (strcasecmp(yytext, "</img") == 0) {
						/* it seems <img></img> couble be same ad <img/> */
						return (HL_C_IMG);
					} else if (strcasecmp(yytext, "</o") == 0) {
						return (HL_C_O);
					} else if (strcasecmp(yytext, "</s") == 0) {
						return (HL_C_S);
					} else if (strcasecmp(yytext, "</sub") == 0) {
						return (HL_C_SUB);
					} else if (strcasecmp(yytext, "</sup") == 0) {
						return (HL_C_SUP);
					} else if (strcasecmp(yytext, "</table") == 0) {
						return (HL_C_TABLE);
					} else if (strcasecmp(yytext, "</th") == 0) {
						/* undocumented that "th" is same as "td" */
						return (HL_C_TD);
					} else if (strcasecmp(yytext, "</td") == 0) {
						return (HL_C_TD);
					} else if (strcasecmp(yytext, "</tr") == 0) {
						return (HL_C_TR);
					} else if (strcasecmp(yytext, "</u") == 0) {
						return (HL_C_U);
					} else if (strcasecmp(yytext, "</vr") == 0) {
						/* it seems <vr></vr> could be same as <vr/> */
						return (HL_C_VR);
					} else {
						/* this is a unknown end tag */
						memset(dp_errmsg, 0, 256);
						snprintf(dp_errmsg, (256 - 1),
							 "%s(): unknown end tag `%s' in html string at line %d\n", __func__, yytext,
							 hllineno);
						return (EOF);
					}
				}
				YY_BREAK case 8:YY_RULE_SETUP
#line 240 "dphl.l"
				{
					/* end tag for br and hr, vr and img */
					hlylval.string = dp_uniqstr(yytext);
					return (HL_SC);
				} YY_BREAK case 9:YY_RULE_SETUP
#line 246 "dphl.l"
				{
					/* end tag for others */
					hlylval.string = dp_uniqstr(yytext);
					return (HL_C);
				} YY_BREAK case 10:YY_RULE_SETUP
#line 252 "dphl.l"
				{
					/* as in var=value */
					hlylval.string = dp_uniqstr(yytext);
					return (HL_IS);
				} YY_BREAK case 11:
/* rule 11 can match eol */
				 YY_RULE_SETUP
#line 258 "dphl.l"
				{
					/* "string" as in var="value" */
					if (strlen(yytext) == 2) {
						hlylval.string = dp_uniqstr("");
						return (HL_QSTR);
					}
					/* create copy buffer */ tmp = dp_calloc(1, (yyleng + 1));
					/* wipe last double quote */
					yytext[yyleng - 1] = 0;
					/* copy past first char */
					pt = yytext;
					pt++;
					q = tmp;
					while (*pt) {
						if (*pt == '\\') {
							if (*(pt + 1) == 0) {
								*q = '\\';
								q++;
								pt++;
							} else if (*(pt + 1) == '\n') {
								/* skip \\n */
								pt = pt + 2;
							} else if (*(pt + 1) == '"') {
								/* \" becomes " */
								*q = '"';
								q++;
								pt = pt + 2;
							} else if (*(pt + 1) == '\\') {
								/* \\ becomes \ */
								*q = '\\';
								q++;
								pt = pt + 2;
							} else {
								*q = '\\';
								q++;
								*q = *(pt + 1);
								q++;
								pt = pt + 2;
							}
						} else {
							/* copy regular chars */
							*q = *pt;
							pt++;
							q++;
						}
					}
					hlylval.string = dp_uniqstr(tmp);
					dp_free(tmp);
					tmp = NULL;
					pt = NULL;
					q = NULL;
					return (HL_QSTR);
				}
				YY_BREAK case 12:
/* rule 12 can match eol */
				 YY_RULE_SETUP
#line 314 "dphl.l"
				{
					/* 'string' as in var='value' */
					if (strlen(yytext) == 2) {
						hlylval.string = dp_uniqstr("");
						return (HL_QSTR);
					}
					/* create copy buffer */ tmp = dp_calloc(1, (yyleng + 1));
					/* wipe last quote */
					yytext[yyleng - 1] = 0;
					/* copy past first char */
					pt = yytext;
					pt++;
					q = tmp;
					while (*pt) {
						if (*pt == '\\') {
							if (*(pt + 1) == 0) {
								*q = '\\';
								q++;
								pt++;
							} else if (*(pt + 1) == '\n') {
								/* skip \\n */
								pt = pt + 2;
							} else if (*(pt + 1) == '\'') {
								/* \' becomes ' */
								*q = '\'';
								q++;
								pt = pt + 2;
							} else if (*(pt + 1) == '\\') {
								/* \\ becomes \ */
								*q = '\\';
								q++;
								pt = pt + 2;
							} else {
								*q = '\\';
								q++;
								*q = *(pt + 1);
								q++;
								pt = pt + 2;
							}
						} else {
							/* copy regular chars */
							*q = *pt;
							pt++;
							q++;
						}
					}
					hlylval.string = dp_uniqstr(tmp);
					dp_free(tmp);
					tmp = NULL;
					pt = NULL;
					q = NULL;
					return (HL_QSTR);
				}
				YY_BREAK case 13:YY_RULE_SETUP
#line 370 "dphl.l"
				{
					/* var */
					hlylval.string = dp_uniqstr(yytext);
					switch (*yytext) {
					case 'a':
					case 'A':
						if (strcasecmp(yytext, "align") == 0) {
							return (HL_ALIGN);
						}
						break;
					case 'b':
					case 'B':
						if (strcasecmp(yytext, "balign") == 0) {
							return (HL_BALIGN);
						} else if (strcasecmp(yytext, "bgcolor") == 0) {
							return (HL_BGCOLOR);
						} else if (strcasecmp(yytext, "border") == 0) {
							return (HL_BORDER);
						} else {
							/* unknown */
						}
						break;
					case 'c':
					case 'C':
						if (strcasecmp(yytext, "cellborder") == 0) {
							return (HL_CELLBORDER);
						} else if (strcasecmp(yytext, "cellpadding") == 0) {
							return (HL_CELLPADDING);
						} else if (strcasecmp(yytext, "cellspacing") == 0) {
							return (HL_CELLSPACING);
						} else if (strcasecmp(yytext, "color") == 0) {
							return (HL_COLOR);
						} else if (strcasecmp(yytext, "columns") == 0) {
							return (HL_COLUMNS);
						} else if (strcasecmp(yytext, "colspan") == 0) {
							return (HL_COLSPAN);
						} else {
							/* unknown */
						}
						break;
					case 'f':
					case 'F':
						if (strcasecmp(yytext, "face") == 0) {
							return (HL_FACE);
						} else if (strcasecmp(yytext, "fixedsize") == 0) {
							return (HL_FIXEDSIZE);
						} else {
							/* unknown */
						}
						break;
					case 'g':
					case 'G':
						if (strcasecmp(yytext, "gradientangle") == 0) {
							return (HL_GRADIENTANGLE);
						}
						break;
					case 'h':
					case 'H':
						if (strcasecmp(yytext, "height") == 0) {
							return (HL_HEIGHT);
						} else if (strcasecmp(yytext, "href") == 0) {
							return (HL_HREF);
						} else {
							/* unknown */
						}
						break;
					case 'i':
					case 'I':
						if (strcasecmp(yytext, "id") == 0) {
							return (HL_ID);
						}
						break;
					case 'p':
					case 'P':
						if (strcasecmp(yytext, "point-size") == 0) {
							return (HL_POINTSIZE);
						} else if (strcasecmp(yytext, "pointsize") == 0) {
							return (HL_POINTSIZE);
						} else if (strcasecmp(yytext, "port") == 0) {
							return (HL_PORT);
						} else {
							/* unknown */
						}
						break;
					case 'r':
					case 'R':
						if (strcasecmp(yytext, "rows") == 0) {
							return (HL_ROWS);
						} else if (strcasecmp(yytext, "rowspan") == 0) {
							return (HL_ROWSPAN);
						} else {
							/* unknown */
						}
						break;
					case 's':
					case 'S':
						if (strcasecmp(yytext, "scale") == 0) {
							return (HL_SCALE);
						} else if (strcasecmp(yytext, "sides") == 0) {
							return (HL_SIDES);
						} else if (strcasecmp(yytext, "src") == 0) {
							return (HL_SRC);
						} else if (strcasecmp(yytext, "style") == 0) {
							return (HL_STYLE);
						} else {
							/* unknown */
						}
						break;
					case 't':
					case 'T':
						if (strcasecmp(yytext, "target") == 0) {
							return (HL_TARGET);
						} else if (strcasecmp(yytext, "title") == 0) {
							return (HL_TITLE);
						} else if (strcasecmp(yytext, "tooltip") == 0) {
							return (HL_TOOLTIP);
						} else {
							/* unknown */
						}
						break;
					case 'v':
					case 'V':
						if (strcasecmp(yytext, "valign") == 0) {
							return (HL_VALIGN);
						}
						break;
					case 'w':
					case 'W':
						if (strcasecmp(yytext, "width") == 0) {
							return (HL_WIDTH);
						}
						break;
					default:
						/* unknown */
						break;
					}
					/* unknown */
					return (HL_STR);
				}
				YY_BREAK case YY_STATE_EOF(INITIAL):
#line 511 "dphl.l"
				{
					/* end of buffer */
					return (EOF);
				}
				YY_BREAK case 14:YY_RULE_SETUP
#line 516 "dphl.l"
				{
					/* something unknown causes parse error */
					return ((int)yytext[0]);
				} YY_BREAK case 15:YY_RULE_SETUP
#line 521 "dphl.l"
				 ECHO;
				YY_BREAK
#line 1716 "lex.hl.c"
			case YY_END_OF_BUFFER:
				{
					/* Amount of text matched not including the EOB char. */
					int yy_amount_of_matched_text = (int)(yy_cp - (yytext_ptr)) - 1;

					/* Undo the effects of YY_DO_BEFORE_ACTION. */
					*yy_cp = (yy_hold_char);
					YY_RESTORE_YY_MORE_OFFSET if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW) {
						/* We're scanning a new file or input source.  It's
						 * possible that this happened because the user
						 * just pointed yyin at a new source and called
						 * yylex().  If so, then we have to assure
						 * consistency between YY_CURRENT_BUFFER and our
						 * globals.  Here is the right place to do so, because
						 * this is the first action (other than possibly a
						 * back-up) that will match for the new input source.
						 */
						(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
						YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
/* %endif */
/* %if-c++-only */
/* %endif */
						YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
					}

					/* Note that here we test for yy_c_buf_p "<=" to the position
					 * of the first EOB in the buffer, since yy_c_buf_p will
					 * already have been incremented past the NUL character
					 * (since all states make transitions on EOB to the
					 * end-of-buffer state).  Contrast this with the test
					 * in input().
					 */
					if ((yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)]) {	/* This was really a NUL. */
						yy_state_type yy_next_state;

						(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

						yy_current_state = yy_get_previous_state();

						/* Okay, we're now positioned to make the NUL
						 * transition.  We couldn't have
						 * yy_get_previous_state() go ahead and do it
						 * for us because it doesn't know how to deal
						 * with the possibility of jamming (and we don't
						 * want to build jamming into it because then it
						 * will run more slowly).
						 */

						yy_next_state = yy_try_NUL_trans(yy_current_state);

						yy_bp = (yytext_ptr) + YY_MORE_ADJ;

						if (yy_next_state) {
							/* Consume the NUL. */
							yy_cp = ++(yy_c_buf_p);
							yy_current_state = yy_next_state;
							goto yy_match;
						}

						else {
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
							yy_cp = (yy_last_accepting_cpos);
							yy_current_state = (yy_last_accepting_state);
							goto yy_find_action;
						}
					}

					else
						switch (yy_get_next_buffer()) {
						case EOB_ACT_END_OF_FILE:
							{
								(yy_did_buffer_switch_on_eof) = 0;

								if (yywrap()) {
									/* Note: because we've taken care in
									 * yy_get_next_buffer() to have set up
									 * yytext, we can now set up
									 * yy_c_buf_p so that if some total
									 * hoser (like flex itself) wants to
									 * call the scanner after we return the
									 * YY_NULL, it'll still work - another
									 * YY_NULL will get returned.
									 */
									(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

									yy_act = YY_STATE_EOF(YY_START);
									goto do_action;
								}

								else {
									if (!(yy_did_buffer_switch_on_eof))
										YY_NEW_FILE;
								}
								break;
							}

						case EOB_ACT_CONTINUE_SCAN:
							(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

							yy_current_state = yy_get_previous_state();

							yy_cp = (yy_c_buf_p);
							yy_bp = (yytext_ptr) + YY_MORE_ADJ;
							goto yy_match;

						case EOB_ACT_LAST_MATCH:
							(yy_c_buf_p) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

							yy_current_state = yy_get_previous_state();

							yy_cp = (yy_c_buf_p);
							yy_bp = (yytext_ptr) + YY_MORE_ADJ;
							goto yy_find_action;
						}
					break;
				}

			default:
				YY_FATAL_ERROR("fatal flex scanner internal error--no action found");
				break;
			}	/* end of action switch */
		}		/* end of scanning one token */
	}			/* end of user's declarations */
}				/* end of yylex */

/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer(void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ((yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1])
		YY_FATAL_ERROR("fatal flex scanner internal error--end of buffer missed");

	if (YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0) {	/* Don't try to fill the buffer, so this is an EOF. */
		if ((yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1) {
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
		}

		else {
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
		}
	}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int)((yy_c_buf_p) - (yytext_ptr) - 1);

	for (i = 0; i < number_to_move; ++i)
		*(dest++) = *(source++);

	if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING)
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else {
		int num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while (num_to_read <= 0) {	/* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset = (int)((yy_c_buf_p) - b->yy_ch_buf);

			if (b->yy_is_our_buffer) {
				int new_size = b->yy_buf_size * 2;

				if (new_size <= 0)
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
				    /* Include room in for 2 EOB chars. */
				    yyrealloc((void *)b->yy_ch_buf, (yy_size_t) (b->yy_buf_size + 2));
			} else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if (!b->yy_ch_buf)
				YY_FATAL_ERROR("fatal error - scanner input buffer overflow");

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		}

		if (num_to_read > YY_READ_BUF_SIZE)
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT((&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]), (yy_n_chars), num_to_read);

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	if ((yy_n_chars) == 0) {
		if (number_to_move == YY_MORE_ADJ) {
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin);
		}

		else {
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_EOF_PENDING;
		}
	}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *)yyrealloc((void *)YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,
									(yy_size_t) new_size);
		if (!YY_CURRENT_BUFFER_LVALUE->yy_ch_buf)
			YY_FATAL_ERROR("out of dynamic memory in yy_get_next_buffer()");
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int)(new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
static yy_state_type yy_get_previous_state(void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;

/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for (yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp) {
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if (yy_accept[yy_current_state]) {
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}
		while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
			yy_current_state = (int)yy_def[yy_current_state];
			if (yy_current_state >= 40)
				yy_c = yy_meta[yy_c];
		}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
static yy_state_type yy_try_NUL_trans(yy_state_type yy_current_state)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
	/* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if (yy_accept[yy_current_state]) {
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
	}
	while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state) {
		yy_current_state = (int)yy_def[yy_current_state];
		if (yy_current_state >= 40)
			yy_c = yy_meta[yy_c];
	}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 39);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput(void)
#else
static int input(void)
#endif
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;

	*(yy_c_buf_p) = (yy_hold_char);

	if (*(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR) {
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ((yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)])
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else {		/* need more input */
			int offset = (int)((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch (yy_get_next_buffer()) {
			case EOB_ACT_LAST_MATCH:
				/* This happens because yy_g_n_b()
				 * sees that we've accumulated a
				 * token and flags that we need to
				 * try matching the token before
				 * proceeding.  But for input(),
				 * there's no matching to consider.
				 * So convert the EOB_ACT_LAST_MATCH
				 * to EOB_ACT_END_OF_FILE.
				 */

				/* Reset buffer status. */
				yyrestart(yyin);

			 /*FALLTHROUGH*/ case EOB_ACT_END_OF_FILE:
				{
					if (yywrap())
						return 0;

					if (!(yy_did_buffer_switch_on_eof))
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) = (yytext_ptr) + offset;
				break;
			}
		}
	}

	c = *(unsigned char *)(yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */
	if (c == '\n')
		yylineno++;
	;

	return c;
}

/* %if-c-only */
#endif /* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
void yyrestart(FILE * input_file)
/* %endif */
/* %if-c++-only */
/* %endif */
{

	if (!YY_CURRENT_BUFFER) {
		yyensure_buffer_stack();
		YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE);
	}

	yy_init_buffer(YY_CURRENT_BUFFER, input_file);
	yy_load_buffer_state();
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer)
/* %endif */
/* %if-c++-only */
/* %endif */
{

	/* TODO. We should be able to replace this entire function body
	 * with
	 *              yypop_buffer_state();
	 *              yypush_buffer_state(new_buffer);
	 */
	yyensure_buffer_stack();
	if (YY_CURRENT_BUFFER == new_buffer)
		return;

	if (YY_CURRENT_BUFFER) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state(void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
/* %endif */
/* %if-c++-only */
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
YY_BUFFER_STATE yy_create_buffer(FILE * file, int size)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yyalloc(sizeof(struct yy_buffer_state));
	if (!b)
		YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *)yyalloc((yy_size_t) (b->yy_buf_size + 2));
	if (!b->yy_ch_buf) {
		yyfree(b);
		YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");
	}

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b, file);

	return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
void yy_delete_buffer(YY_BUFFER_STATE b)
/* %endif */
/* %if-c++-only */
/* %endif */
{

	if (!b)
		return;

	if (b == YY_CURRENT_BUFFER)	/* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if (b->yy_is_our_buffer)
		yyfree((void *)b->yy_ch_buf);

	yyfree((void *)b);
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
static void yy_init_buffer(YY_BUFFER_STATE b, FILE * file)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int oerrno = errno;

	if (b == NULL) {
		/* shouldnothappen */
		return;
	}

	yy_flush_buffer(b);

/* %if-c-only */
	b->yy_input_file = file;
/* %endif */
/* %if-c++-only */
/* %endif */
	b->yy_fill_buffer = 1;

	/* If b is the current buffer, then yy_init_buffer was _probably_
	 * called from yyrestart() or through yy_get_next_buffer.
	 * In that case, we don't want to reset the lineno or column.
	 */
	if (b != YY_CURRENT_BUFFER) {
		b->yy_bs_lineno = 1;
		b->yy_bs_column = 0;
	}

	/* %if-c-only */

	b->yy_is_interactive = 0;

/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
void yy_flush_buffer(YY_BUFFER_STATE b)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	if (!b)
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if (b == YY_CURRENT_BUFFER)
		yy_load_buffer_state();
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state(YY_BUFFER_STATE new_buffer)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if (YY_CURRENT_BUFFER) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state();
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state(void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state();
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack(void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;

	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
		 */
		num_to_alloc = 1;	/* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state **)yyalloc(num_to_alloc * sizeof(struct yy_buffer_state *)
		    );
		if (!(yy_buffer_stack))
			YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state *));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */ ;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state **)yyrealloc
		    ((yy_buffer_stack), num_to_alloc * sizeof(struct yy_buffer_state *)
		    );
		if (!(yy_buffer_stack))
			YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

		/* zero only the new slots. */
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state *));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer(char *base, yy_size_t size)
{
	YY_BUFFER_STATE b;

	if (size < 2 || base[size - 2] != YY_END_OF_BUFFER_CHAR || base[size - 1] != YY_END_OF_BUFFER_CHAR)
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof(struct yy_buffer_state));
	if (!b) {
		YY_FATAL_ERROR("out of dynamic memory in yy_scan_buffer()");
	}

	b->yy_buf_size = (int)(size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b);

	return b;
}

/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string(const char *yystr)
{

	return yy_scan_bytes(yystr, (int)strlen(yystr));
}

/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes(const char *yybytes, int _yybytes_len)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *)yyalloc(n);
	if (!buf)
		YY_FATAL_ERROR("out of dynamic memory in yy_scan_bytes()");

	for (i = 0; i < _yybytes_len; ++i)
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len + 1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf, n);
	if (!b) {
		yyfree(buf);
		YY_FATAL_ERROR("bad buffer in yy_scan_bytes()");
	}

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error(const char *msg)
{
	fprintf(stderr, "%s\n", msg);
	exit(YY_EXIT_FAILURE);
}

/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno(void)
{

	return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in(void)
{
	return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out(void)
{
	return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng(void)
{
	return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text(void)
{
	return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno(int _line_number)
{

	yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in(FILE * _in_str)
{
	yyin = _in_str;
}

void yyset_out(FILE * _out_str)
{
	yyout = _out_str;
}

int yyget_debug(void)
{
	return yy_flex_debug;
}

void yyset_debug(int _bdebug)
{
	yy_flex_debug = _bdebug;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals(void)
{
	/* Initialization is the same as for the non-reentrant scanner.
	 * This function is called from yylex_destroy(), so don't allocate here.
	 */

	/* We do not touch yylineno unless the option is enabled. */
	yylineno = 1;

	(yy_buffer_stack) = NULL;
	(yy_buffer_stack_top) = 0;
	(yy_buffer_stack_max) = 0;
	(yy_c_buf_p) = NULL;
	(yy_init) = 0;
	(yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
	yyin = stdin;
	yyout = stdout;
#else
	yyin = NULL;
	yyout = NULL;
#endif

	/* For future reference: Set errno on error, since we are called by
	 * yylex_init()
	 */
	return 0;
}

/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy(void)
{

	/* Pop the buffer stack, destroying each element. */
	while (YY_CURRENT_BUFFER) {
		yy_delete_buffer(YY_CURRENT_BUFFER);
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack));
	(yy_buffer_stack) = NULL;

	/* Reset the globals. This is important in a non-reentrant scanner so the next time
	 * yylex() is called, initialization will occur. */
	yy_init_globals();

/* %if-reentrant */
/* %endif */
	return 0;
}

/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy(char *s1, const char *s2, int n)
{

	int i;
	for (i = 0; i < n; ++i)
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(const char *s)
{
	int n;
	for (n = 0; s[n]; ++n) ;

	return n;
}
#endif

void *yyalloc(yy_size_t size)
{
	void *ret = NULL;
	ret = calloc(1, size);
	if (ret == NULL) {
		/* option here to do exit (1); */
	}
	return (ret);
}

void *yyrealloc(void *ptr, yy_size_t size)
{
	void *ret = NULL;
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	ret = realloc(ptr, size);
	if (size) {
		if (ret == NULL) {
			/* option here to do exit (1); */
		}
	}
	return (ret);
}

void yyfree(void *ptr)
{
	if (ptr) {
		free((char *)ptr);
	}			/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 521 "dphl.l"

/* lex buffer */
static YY_BUFFER_STATE buffer = NULL;

/* clear buffer */
static int clearit = 0;

/* lex buffer pending */
static int pending = 0;

/* lex buffer length */
static int buflen = 0;

/* data buffer */
static char *dbuf = (char *)0;

/* tag buffer */
static char *tbuf = (char *)0;

/* input buffer */
static char *ibuf = (char *)0;

/* pointer in ibuf */
static char *bufptr = (char *)0;

/* init
 * the string has at least 1 char as in "< >"
 */
void html_lex_init(int dbg, char *str, int line)
{

	if (dbg || 0) {
		hl_flex_debug = 1;
		hlydebug = 1;
	} else {
		hl_flex_debug = 0;
		hlydebug = 0;
	}

	/* set lineno to where the node is defind */
	hllineno = line;

	/* extra space for \0\0 */
	buflen = strlen(str) + 2;

	ibuf = dp_calloc(1, buflen);

	if (ibuf == NULL) {
		return;
	}

	/* copy, skip first < */
	strcpy(ibuf, (str + 1));

	/* wipe last > */
	ibuf[strlen(ibuf) - 1] = 0;

	/* set where to start lexing */
	bufptr = ibuf;

	/* skip leading ws todo XXX is this always correct? */
	while (*bufptr) {
		if (*bufptr == ' ') {
		} else if (*bufptr == '\n') {
			hllineno++;
		} else if (*bufptr == '\r') {
		} else if (*bufptr == '\f') {
		} else if (*bufptr == '\t') {
		} else {
			break;
		}
		bufptr++;
	}

	skipws = 1;

	/* data buffer */
	dbuf = (char *)dp_calloc(1, buflen);

	if (dbuf == NULL) {
		return;
	}

	/* tag buffer */
	tbuf = (char *)dp_calloc(1, buflen);

	if (tbuf == NULL) {
		return;
	}

	/* lex buffer pending */
	pending = 0;

	/* clear buffer */
	clearit = 0;

	return;
}

/* de-init */
void html_lex_deinit(void)
{

	hl_flex_debug = 0;

	/* clear buffer */
	if (clearit || 1) {
		/* this may fix valgrind issue */
		yylex_destroy();
		/* yy_delete_buffer (buffer); */
		buffer = NULL;
		clearit = 0;
	}

	/* lex buffer pending */
	pending = 0;

	/* lex buffer length */
	buflen = 0;

	/* data buffer */
	if (dbuf) {
		dp_free(dbuf);
		dbuf = (char *)0;
	}

	/* tag buffer */
	if (tbuf) {
		dp_free(tbuf);
		tbuf = (char *)0;
	}

	/* input buffer */
	if (ibuf) {
		dp_free(ibuf);
		ibuf = (char *)0;
	}

	/* pointer in ibuf */
	bufptr = (char *)0;

	return;
}

/* lex one token */
int html_lex(void)
{
	int token = 0;
	int i = 0;
	int j = 0;
	char *p = NULL;

	for (i = 0; i < 100; i++) {
		/* lex buffer pending */
		if (pending == 1) {
			/* lex from buffer */
			token = hllex();
			/* at end-of-string in tbuf */
			if (token == EOF) {
				/* this may fix valgrind issue */
				yylex_destroy();
				/* yy_delete_buffer (buffer); */
				buffer = NULL;
				clearit = 0;
				pending = 0;
				continue;
			}
			/* at regular token */
			pending = 1;
			/* hlylval.string is set in the actions */
			return (token);
		} else {
			/* refill buffer */
			if (*bufptr == 0) {
				/* no data anymore */
				return (EOF);
			}

			if (skipws) {
				/* skip leading ws */
				while (*bufptr) {
					if (*bufptr == ' ') {
					} else if (*bufptr == '\n') {
						hllineno++;
					} else if (*bufptr == '\r') {
					} else if (*bufptr == '\f') {
					} else if (*bufptr == '\t') {
					} else {
						break;
					}
					bufptr++;
				}
			} else {
				skipws = 1;
			}

			if (*bufptr == 0) {
				/* no data anymore */
				return (EOF);
			}

			if (*bufptr == '<') {
				/* fill tag buffer */
				for (j = 0; j < buflen; j++) {
					tbuf[j] = 0;
				}
				j = 0;
				while (*bufptr) {
					if (*bufptr == '>') {
						tbuf[j] = *bufptr;
						j++;
						bufptr++;
						break;
					}
					tbuf[j] = *bufptr;
					j++;
					bufptr++;
				}
				if (j == 0) {
					return (EOF);
				}
				/* start lexing from buffer */
				buffer = yy_scan_string(tbuf);
				clearit = 1;
				/* lex tag buffer */
				pending = 1;
				continue;
			} else {
				/* fill data buffer */
				for (j = 0; j < buflen; j++) {
					dbuf[j] = 0;
				}
				j = 0;
				p = dbuf;
				while (*bufptr) {
					if (*bufptr == '<') {
						break;
					}
					/* update yylineno */
					if (*bufptr == '\n') {
						hllineno++;
					}
					p[j] = *bufptr;
					j++;
					bufptr++;
				}
				if (j == 0) {
					return (EOF);
				}
				pending = 0;
				/* return copy of the data area */
				hlylval.string = dp_uniqstr(dbuf);
				if (hlydebug) {
					printf("token HL_DATA \"%s\"\n", hlylval.string);
				}
				return (HL_DATA);
			}
		}
	}

	/* shouldnothappen */
	printf("%s(): huh?\n", __func__);

	return (EOF);
}

/* end */
