#!/bin/sh -x
rm dot.tab.c
rm dot.tab.h
rm dot.output
rm dot.xml
rm lex.yy.c
echo "generating dot lexer and parser"
flex dot.l
bison -d --graph -x dot.y
echo "generating vcg lexer"
# -d   == add debug code
# -8   == generate 8 bits scanner
# -f   == fast large scanner
# -R   == reentrant lexer for threaded parsing
flex -d -8 -f --yylineno --prefix=vcg --outfile=vcg.flex.c vcg.l
